"""pdf_datetime

Revision ID: 02db9a3fb71d
Revises: 295024eb1dc6
Create Date: 2024-12-08 07:45:15.773079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02db9a3fb71d'
down_revision: Union[str, None] = '295024eb1dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdfs', 'updated_at')
    # ### end Alembic commands ###
